module.exports = [
  { code: 'explorer_hat', label: 'Chapeu de Trilha', emoji: '🤠', price: 15, slot: 'head' },
  { code: 'safari_helmet', label: 'Capacete Safari', emoji: '🪖', price: 50, slot: 'head' },
  { code: 'beanie', label: 'Gorro de Frio', emoji: '🧶', price: 80, slot: 'head' },
  { code: 'crown', label: 'Coroa da Floresta', emoji: '👑', price: 500, slot: 'head' },
  { code: 'flower', label: 'Flor Nativa', emoji: '🌺', price: 20, slot: 'head' },
  { code: 'cap', label: 'Bone do Guarda', emoji: '🧢', price: 40, slot: 'head' },
  { code: 'wizard', label: 'Chapeu Magico', emoji: '🧙', price: 600, slot: 'head' },
  { code: 'headphones', label: 'Fones de Ouvido', emoji: '🎧', price: 90, slot: 'head' },
  { code: 'glasses', label: 'Oculos Cientista', emoji: '👓', price: 30, slot: 'eyes' },
  { code: 'sunglasses', label: 'Oculos de Sol', emoji: '🕶️', price: 45, slot: 'eyes' },
  { code: 'goggles', label: 'Oculos Mergulho', emoji: '🥽', price: 100, slot: 'eyes' },
  { code: 'monocle', label: 'Monoculo Classico', emoji: '🧐', price: 150, slot: 'eyes' },
  { code: 'backpack', label: 'Mochila de Campo', emoji: '🎒', price: 60, slot: 'body' },
  { code: 'vest', label: 'Colete de Guarda', emoji: '🦺', price: 110, slot: 'body' },
  { code: 'lab_coat', label: 'Jaleco de Ciencia', emoji: '🥼', price: 250, slot: 'body' },
  { code: 'tie', label: 'Gravata Borboleta', emoji: '🎀', price: 150, slot: 'body' },
  { code: 'scarf', label: 'Cachecol de La', emoji: '🧣', price: 120, slot: 'body' },
  { code: 'magnifier', label: 'Lupa do Biologo', emoji: '🔍', price: 45, slot: 'hand' },
  { code: 'compass', label: 'Bussola', emoji: '🧭', price: 75, slot: 'hand' },
  { code: 'flashlight', label: 'Lanterna', emoji: '🔦', price: 90, slot: 'hand' },
  { code: 'net', label: 'Rede de Insetos', emoji: '🕸️', price: 135, slot: 'hand' },
  { code: 'map', label: 'Mapa das Matas', emoji: '🗺️', price: 195, slot: 'hand' },
  { code: 'microscope', label: 'Microscopio', emoji: '🔬', price: 230, slot: 'hand' },
  { code: 'notebook', label: 'Diario Cientifico', emoji: '📓', price: 280, slot: 'hand' },
  { code: 'camera', label: 'Camera Pro', emoji: '📷', price: 350, slot: 'hand' },
  { code: 'walkie_talkie', label: 'Radio Amador', emoji: '📻', price: 400, slot: 'hand' },
  { code: 'potion', label: 'Pocao de Cura', emoji: '🧪', price: 450, slot: 'hand' },
  { code: 'sword', label: 'Espada de Graveto', emoji: '🗡️', price: 500, slot: 'hand' },
  { code: 'guitar', label: 'Violao de Acampamento', emoji: '🎸', price: 600, slot: 'hand' },
  { code: 'boots', label: 'Botas de Trilha', emoji: '🥾', price: 160, slot: 'feet' },
  { code: 'rain_boots', label: 'Galochas', emoji: '👢', price: 200, slot: 'feet' },
  { code: 'sneakers', label: 'Tenis Rapido', emoji: '👟', price: 220, slot: 'feet' },
  { code: 'socks', label: 'Meias Quentinhas', emoji: '🧦', price: 100, slot: 'feet' },
  { code: 'skates', label: 'Patins de Asfalto', emoji: '🛼', price: 300, slot: 'feet' }
];